### ISSUE TITLE
Duplicate Writing of MT Number

### ISSUE THREAD

**Issue by abnowack** [njoy/ACEtk#67]
I'm looking to zero out the inelastic collisions of U235. I've noticed that when changing MT=59 in the CrossSectionBlock, MT numbers will be altered in ways I don't believe it should.

[I've uploaded an example as a gist here](https://gist.github.com/abnowack/aef469c2b480b4764148405c62cedfcb)

You can see that 16 is removed, and 15 is added, in the reaction numbers, and additionally a duplicate 58 has been added.

In another script, when I go to read MT=59 in this resulting edited cross section file, I will get an error of "[error] The requested reaction number MT59 is not present" despite it appearing in the list of MT numbers.

This is using the ENDF data distributed with MCNP6.2, which I can attach or email privately if needed.

If I try to load this cross section in MCNP, I will get the following error,
```
 Expire parameter is 
 error 2 in  92235.80c of cross-section file xdata/endf71x/u/92235.710nc

 bad trouble in subroutine sread of xact                              

 error 2 in  92235.80c of cross-section file xdata/endf71x/u/92235.710nc
```

**Comment by whaeck** [comment]
Nice catch. It's actually a coding "flaw", not an error in the ACE file. Allow me to explain.

The ACE file is being printed out as a list of floating point values. MCNP actually reads these into an array of floating point values, and interprets these numbers as integers as required. As you probably know, converting a floating point value into an integer value by implicit casting can be dangerous since some integers cannot be represented properly in a floating point representation (implicit casts tend to round down to the closest integer). In this case, the ACE file contains the value 5.90000000000e+1, which gets cast to 58 because the in memory representation is probably 5.899999999999e+1 (or something similar). In order to extract the correct integer, we actually need to round the float to the closest integer before casting the float to an integer value.

In this case, the C++ function under the hood returns an array of floating points, which on the python side get cast to an array of integer values - which is bad. I actually have to do the rounding on the C++ side.

You can see this behaviour in the following snippet of code:
```
for i in range( 1, ace_file2.NTR + 1 ) :
    
    print( ace_file2.MTR.reaction_number(i), ace_file2.MTR.reaction_numbers[i-1] )
```

The `ace_file2.MTR.reaction_number(i)` does the rounding while `ace_file2.MTR.reaction_numbers[i-1]` only casts under the hood. As you can see when you execute this piece of python code, even the first MT number gets interpreted wrongly: the correct value is 16, not 15.

I need to fix this asap.

Now, for your issue with MCNP, this might be because you are incorrectly copying the secondary particle data. The issue with the MTR array is not causing this (the actual data in the ACE file gives the right values). Allow me to look into this some more.

**Comment by whaeck** [comment]
For the MCNP error, I have compared the xss array that contains the data between the old and new ACE file using this code:
```
import math
xss1 = ace_file.data.xss_array
xss2 = ace_file2.data.xss_array
for i in range( len( xss1 ) ) :
    if xss1[i] != xss2[i] :
        if not math.isclose( xss1[i], xss2[i] ) :
            print( i, xss1[i], xss2[i] )
```

The only differences I see are for where you set the cross section values to zero. All other changes are within roundoff (I use isclose to eliminate those cases).

I do not know why this ACE file is not being accepted by MCNP. I may have to refer it to the MCNP team to understand what is going on.

**Comment by whaeck** [comment]
All block locators are the same between the 2 files as well, so MCNP should accept the file.
