### ISSUE TITLE
Photofission neutron yield information not found for Am-241

### ISSUE THREAD

**Issue by mcdonnelljd** [njoy/ACEtk#74]
Using the ACEtk features/photonuclear branch, secondary particle information for neutrons released from fission (MT=18) are not found for Am-241 (ZA=95241).  From the ENDF file, it is expected that Am-241 would have both multiplicity (MT=452) and energy distribution (MF=5) for photofission neutrons.  

Example script: 
```python
import ACEtk

tables = ACEtk.PhotonuclearTable.from_concatenated_file("xmc/endf7u")

for table in tables:
        if table.reaction_number_block.has_MT(18):
            print("{:} has MT=18".format(table.zaid))
            rb = table.secondary_particle_reaction_number_block(1)
            if rb.has_MT(18):
                print("   fission neutrons present")
            else:
                print("WARNING: {:} does not have fission neutrons".format(table.zaid))
            rb = table.secondary_particle_reaction_number_block(2)
            if rb.has_MT(18):
                print("   fission photons present")
            else:
                print("WARNING: {:} does not have fission photons".format(table.zaid))
```

Example output: 
```bash
92235.70u has MT=18
   fission neutrons present
WARNING: 92235.70u does not have fission photons
92238.70u has MT=18
   fission neutrons present
WARNING: 92238.70u does not have fission photons
93237.70u has MT=18
   fission neutrons present
WARNING: 93237.70u does not have fission photons
94239.70u has MT=18
   fission neutrons present
WARNING: 94239.70u does not have fission photons
94240.70u has MT=18
   fission neutrons present
WARNING: 94240.70u does not have fission photons
95241.70u has MT=18
WARNING: 95241.70u does not have fission neutrons
WARNING: 95241.70u does not have fission photons
```

**Comment by whaeck** [comment]
A summary of the investigations made for this issue:

A cursory review of the ACE file did indeed show that MT18 (fission) is not included in the MTRH block for the secondary neutrons in the Am241 photonuclear ACE file in the endf70u library. It also seems to be the only file without fission neutrons.

A review of the Am241 photonuclear data evaluation showed that there is information for fission neutrons included in the evaluation. Looking into the NJOY2016 source code, we saw that the secondary particle data is added only to the ACE file if the reaction has an entry in either MF4 or MF6 (also, the index in MF1 MT451 is done to determine this - and not the actual data in MF4 or MF6, which means that the index should be correct before processing). A comparison with U235 photonuclear data data showed that MF4 MT18 should be given to fix the issue during processing(even though the entry just sets the angular distribution to be isotropic).

A modified evaluation file was produced - but now NJOY does not process the file at all since the MF5 MT18 data uses an unsupported representation type. See the following issue in NJOY2016: https://github.com/njoy/NJOY2016/issues/269
